services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - ../data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U media" ]
      interval: 1s
      timeout: 5s
      retries: 10

  dbmanager:
    build: 
      context: .
      dockerfile: ./dbmanager/Dockerfile
    env_file:
      - .env
    volumes:
    - ../data/json:/data
    - ../data/dbschema:/schema
    ports:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck || exit 1
      interval: 1s
      timeout: 5s
      retries: 10

  clientserver:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      dbmanager:
        condition: service_healthy
        restart: true
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck || exit 1
      interval: 1s
      timeout: 5s
      retries: 10      